config/routes.rb
Rails.application.routes.draw do
	root 'users#new'
	get '/' => 'users#new'

	get '/tags' => 'tags#index'
  get '/tags/new' => 'tags#new', as: :new_tag
  get '/tags/:id/edit' => 'tags#edit', as: :edit_tag 
  patch '/tags/:id' => 'tags#update'
	get '/tags/:id' => 'tags#show', as: :tag
  post '/tags' => 'tags#create'

  get '/tags/:id/new' => 'destinations#new', as: :new_destination
	post '/tags/:id/new' => 'destinations#create'
  get '/product' => 'destinations#index'
  get '/product/new' =>  'destinations#new', as: :create_destination
  get '/product/:id' => 'destinations#show', as: :destination	
	get '/product/:id/edit' => 'destinations#edit', as: :edit_destination
	patch '/product/:id' => 'destinations#update'

	get 'signup' => 'users#new'
  get '/users' => 'users#index', as: :users
  get '/profile/:id/edit' => 'users#edit', as: :edit_user
  patch '/profile/:id' => 'users#update'
  get '/profile/:id' => 'users#show', as: :profile

	get '/login' => 'sessions#new'
	post '/login' =>'sessions#create'	
	delete 'logout' => 'sessions#destroy'

  get '/brands' => 'countries#index', as: :country_index
  get '/brands/new' => 'countries#new', as: :create_country
  get '/brands/:id/edit' => 'countries#edit', as: :edit_country
  get '/brands/:id/new' => 'tags#new', as: :tag_in_country
  patch '/brands/:id' => 'countries#update'
  get '/brands/:id' => 'countries#show', as: :country

  get '/messages' => 'messages#index', as: :messages
  post '/messages' => 'messages#create'

  get '/tips/:id/edit' => 'tips#edit', as: :edit_tip
  get '/tips' => 'tips#index', as: :tips
  get '/tips/new' => 'tips#new', as: :tip_new
  post '/tips' => 'tips#create'
  patch '/tips/:id' => 'tips#update'

  resources :users, only: [:index, :edit, :update, :create, :destroy]
  resources :countries, only: [:index, :edit, :update, :create, :destroy]
  resources :tags, only: [:index, :show, :edit, :update, :create, :destroy]
  resources :destinations, only: [:show, :edit, :update, :create, :destroy]
  resources :tips, only: [:create]
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :tags

	
end

app/models/destination.rb
class Destination < ActiveRecord::Base
	belongs_to :tag
	has_many :messages
	has_many :tips
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :destination
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	belongs_to :country
	has_many :destinations
end

app/models/tip.rb
class Tip < ActiveRecord::Base
	belongs_to :destination
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	has_many :tips
	
	def editor?
		self.role == 'editor'
	end

	def admin?
		self.role == 'admin'
	end

	def super?
		self.role == 'super'
	end
	

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
	before_action :require_user, only: [:index, :show]
	before_action :require_editor, only: [:edit, :new]
	before_action :require_admin, only: [:destroy]

	def index
		@countries = Country.all
	end

	def show
		@country = Country.find(params[:id])
		@tags = @country.tags
	end

	def new
		@country = Country.new
	end


	def create
		t = Time.now.strftime("%Y%m%d%H%M%S")
		uploaded_io = params[:country][:image]
        File.open(Rails.root.join('public', 'uploads', 'countries', uploaded_io.original_filename), 'wb') do |file|
     	file.write(uploaded_io.read)
        end

		@country = Country.new(country_params)
		if @country.save
			redirect_to "/countries", notice: "Country created successfully!"
		else
			redirect_to root_path, error: "Country was not created."
		end
	end

	def edit
		@country = Country.find(params[:id])
	end

	def update
		@country = Country.find(params[:id])
		if @country.update_attributes(country_params)
			redirect_to "/countries", notice: "Country updated successfully"
		else
			render "edit", error: "Country has not been updated."
		end
	end


	def destroy
		@country = Country.find(params[:id])
		@country.destroy
		redirect_to "/countries", notice: "Country destroyed successfully!"
	end

	def upload
            uploaded_io = country_params
            File.open(Rails.root.join('public', 'uploads', 'countries', uploaded_io.original_filename), 'wb') do |file|
            file.write(uploaded_io.read)
            end
    end

	private

	def country_params
		params.require(:country).permit(:title,:image)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	helper_method :destination 
	
	def new
		@message= Message.new
	end

	def create
		@message = Message.new(message_params)
		@message.user_id = current_user.id
		@message.destination_id = :destination
		if @message.save
			redirect_to "/destinations"
		else
			flash.now[:error] = "error"
		end
	end

	private
	def message_params
		params.require(:message).permit(:content,:user_id, :destination_id)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_action :require_user, only: [:index, :show]
	before_action :require_editor, only: [:edit, :new]
	before_action :require_admin, only: [:destroy]


	def index
	 @tags = Tag.all
	end
	
	def show
	 @tag = Tag.find(params[:id])
	 @destinations = @tag.destinations	
	end
	
	def new
		@tag = Tag.new
	end

	def create
		t = Time.now.strftime("%Y%m%d%H%M%S")
		uploaded_io = params[:tag][:image]
        File.open(Rails.root.join('public', 'uploads', 'tags', uploaded_io.original_filename), 'wb') do |file|
     	file.write(uploaded_io.read)
        end

		@tag = Tag.new(tag_params)
		@tag.country_id = country_path(:id)
		if @tag.save
			redirect_to "/tags", notice: "Tag created successfully!"
		else
			redirect_to "/tags/new"

		end

	end

	def edit
		@tag = Tag.find(params[:id])
	end

	def update
		@tag = Tag.find(params[:id])
		if @tag.update_attributes(tag_params)
		redirect_to "/tags", notice: "Tag updated successfully!"
		else
		render 'edit'
		end	
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy
		redirect_to "/tags", alert: "Tag destroyed successfully!"
	end

	private
	
	def tag_params
		params.require(:tag).permit(:title, :image, :country_id)
	end

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
	def index
		@tips = Tip.all
	end

	def new
		@tip = Tip.new
	end

	def create
		@tip = Tip.new(tip_params)
		@tip.user_id = current_user.id
		if @tip.save
			redirect_to "/tips"
		else
			render "new"
		end
	end

	def edit
		@tip = Tip.find(params[:id])
	end

	def update
		@tip = Tip.find(params[:id])
		if 

			@tip.update_attributes(tip_params)
			redirect_to '/tips', notice: 'Tip updated successfully'
		else
			render 'edit'
		end
	end

	def destroy
		@tip = Tip.find(params[:id])
		@tip.destroy
		redirect_to '/tips', alert: 'Tip destroyed successfully'
	end

	private
	def tip_params
		params.require(:tip).permit(:content, :user_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_user, only: [:show]
	before_action :require_super, only: [:index]
	before_action :require_owner, only: [:edit]
	
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id]=@user.id
			redirect_to '/'
		else
			redirect_to '/signup'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
		redirect_to profile_path, notice: "User info updated successfully!"
		else
		render 'edit'
		end	
	end

	def destroy 
		@user = User.find(params[:id])
		@user.destroy
		redirect_to "/users", alert: "User destroyed successfully!"
	end
	
	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :role)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/destination_helper.rb
module DestinationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/countries/edit.html.erb
<div class="country">
	<div class="container">
		<div class="edit-form">
			<div class="app-nav">
				<%= link_to country_index_path do %>
				<i class="material-icons">chevron_left</i>
				<% end %>
			</div>
			<img class="img-responsive" src="<%= @country.image %>"/>
			<%= form_for(@country) do |f| %>
			<div class="form-group">
				<label for="image"> Image Url </edit>
				<%= f.text_field :image %>
				<label for="country"> Brand Name </label>
				<%= f.text_field :title %>
				<div class="submit">
				<%= f.submit "Update", :class => "btn-submit", :id => "btn" %>
				<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/countries/index.html.erb
<div class="countries">
	<div class="page-nav">
		<div class="dropdown">
 			<button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   				<i class="material-icons" id="filter">filter_list</i>
    			<span class="caret"></span>
  			</button>
  			<ul class="dropdown-menu" id="filter-menu" aria-labelledby="dLabel">
    			<li><i class="material-icons">sort_by_alpha</i>Name</li>
				<li><i class="material-icons">favorite</i>Most Visited</li>
				<li><i class="material-icons">whatshot</i>Hottest</li>
				<li><i class="material-icons">trending_up</i>Trending</li>
				<li><i class="material-icons">my_location</i>Near Me</li>
  			</ul>
		</div>
		<h2> Brands </h2>
		<ul class="pull-right">
			<li class="square"><i class="material-icons" id="square">reorder</i></li>
			<li class="squares"><i class="material-icons">apps</i></li>
		</ul>
	</div>

	<div class="container">
		<div class="col-md-4 col-xs-4 col-md-offset-8 col-xs-offset-3">
			<% flash.each do |name, msg| -%>
    		<%= content_tag :div, msg, class: name %>
    		<% end -%>	
		</div>
		<div class="app-nav">
			<% if current_user && current_user.admin? || current_user.editor?() %>
				<%= link_to create_country_path(@new) do %>
					<i class="material-icons">add_circle</i>
				<% end %>
			<% end %>
		</div>
		<div class="cards row">
			<% @countries.each do |c| %>
			<div class="card col-md-3 col-xs-10">
				<img class="img-responsive" id="tags" src="<%= c.image %>"/>
				<h2><%= c.title %></h2>
				<%= link_to country_path(c) do %>
				<div class="card-action">
					<i class="material-icons">explore</i>
				<% end %>
				<i class="material-icons">favorite_border</i>
				<%= link_to root_path(c) do %>
					<i class="material-icons">location_on</i>
				<% end %>
				<%= link_to root_path(c) do %>
					<i class="material-icons">loyalty</i>
				<% end %>
				<% if current_user && current_user.admin?() %>
					<%= link_to country_path(c), method: "delete", data: {confirm: "Are you sure you want to delete this?"} do %>
						<i class="material-icons">delete_forever</i>
					<% end %>	
				<% end %>	
				<% if current_user && current_user.admin? || current_user.editor?() %>
					<%= link_to edit_country_path(c) do %>
					<i class="material-icons">mode_edit</i>
					<% end %>
				<% end %>
				</div>		
			</div>
			<% end %>
		</div>
	</div>
</div>
<div class="clear-fix">
</div>

app/views/countries/new.html.erb
<div class="country-new">
	<div class="container">
		<div class="app-nav">
			<%= link_to "/brands" do %>
				<i class="material-icons">chevron_left</i>
			<% end %>
		</div>
		<h1> New Brand</h1>
		<%= form_for(@country) do |t| %>
		<label for="image">Image</label>
		<%= t.file_field :image, :placeholder => "image" %>
		<p class="help-block">Max image size: 3 megabytes</p>
		 <label for="title">Title</label>
		<%= t.text_field :title, :placeholder => "Title" %>
		<div class="submit">
			<%= t.submit "Create Country", class: "btn-submit", method: "create" %>
			<% end %> 
		</div>
	</div>
</div>
<div class="clear-fix">
</div>

app/views/countries/show.html.erb
<div class="countries">
	<div class="page-nav">
		<div class="dropdown">
 			<button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   				<i class="material-icons" id="filter">filter_list</i>
    			<span class="caret"></span>
  			</button>
  			<ul class="dropdown-menu" id="filter-menu" aria-labelledby="dLabel">
    			<li><i class="material-icons">sort_by_alpha</i>Name</li>
				<li><i class="material-icons">favorite</i>Most Visited</li>
				<li><i class="material-icons">whatshot</i>Hottest</li>
				<li><i class="material-icons">trending_up</i>Trending</li>
				<li><i class="material-icons">my_location</i>Near Me</li>
  			</ul>
		</div>
		<h2><%= @country.title %></h2>
		<ul class="pull-right">
			<li class="square"><i class="material-icons" id="square">reorder</i></li>
			<li class="squares"><i class="material-icons">apps</i></li>
		</ul>
	</div>
	<div class="container">
 		<div class="app-nav">
			<%= link_to "/brands" do %>
				<i class="material-icons">chevron_left</i>
			<% end %>
		</div>
 		<div class="col-md-4 col-xs-4 col-md-offset-8 col-xs-offset-3">
			<% flash.each do |name, msg| -%>
    		<%= content_tag :div, msg, class: name %>
    		<% end -%>
		</div>
   		<div class="app-nav">
   			<% if current_user.admin? || current_user.editor?() %>
   				<%= link_to tag_in_country_path do %> 
   					<i class="material-icons">add_circle</i>
				<% end %>
			<% end %>
		</div>

   		<div class = "cards row">
			<% @tags.each do |t| %>
    		<div class= "card col-md-3 col-xs-11">
				<img class="img-responsive" id="tags" src="<%= t.image %>">
				<h2><%= t.title %></h2>
				<div class="card-action">
				<%= link_to tag_path(t) do %>
					<i class="material-icons">explore</i>
				<% end %>
				<i class="material-icons">favorite_border</i>
				<%= link_to tag_path(t) do %>
					<i class="material-icons">location_on</i>
				<% end %>
				<%= link_to tag_path(t) do %>
					<i class="material-icons">loyalty</i>
				<% end %>
				</div>		
			</div>
			<% end %>
   		</div>		
 	</div>
</div>
<div class="clear-fix">
</div>