config/routes.rb
Rails.application.routes.draw do
	root 'users#new'
	get '/' => 'users#new'

	get '/tags' => 'tags#index'
  get '/tags/new' => 'tags#new', as: :new_tag
  get '/tags/:id/edit' => 'tags#edit', as: :edit_tag 
  patch '/tags/:id' => 'tags#update'
	get '/tags/:id' => 'tags#show', as: :tag
  post '/tags' => 'tags#create'

  get '/tags/:id/new' => 'destinations#new', as: :new_destination
	post '/tags/:id/new' => 'destinations#create'
  get '/product' => 'destinations#index'
  get '/product/new' =>  'destinations#new', as: :create_destination
  get '/product/:id' => 'destinations#show', as: :destination	
	get '/product/:id/edit' => 'destinations#edit', as: :edit_destination
	patch '/product/:id' => 'destinations#update'

	get 'signup' => 'users#new'
  get '/users' => 'users#index', as: :users
  get '/profile/:id/edit' => 'users#edit', as: :edit_user
  patch '/profile/:id' => 'users#update'
  get '/profile/:id' => 'users#show', as: :profile

	get '/login' => 'sessions#new'
	post '/login' =>'sessions#create'	
	delete 'logout' => 'sessions#destroy'

  get '/brands' => 'countries#index', as: :country_index
  get '/brands/new' => 'countries#new', as: :create_country
  get '/brands/:id/edit' => 'countries#edit', as: :edit_country
  get '/brands/:id/new' => 'tags#new', as: :tag_in_country
  patch '/brands/:id' => 'countries#update'
  get '/brands/:id' => 'countries#show', as: :country

  get '/messages' => 'messages#index', as: :messages
  post '/messages' => 'messages#create'

  get '/tips/:id/edit' => 'tips#edit', as: :edit_tip
  get '/tips' => 'tips#index', as: :tips
  get '/tips/new' => 'tips#new', as: :tip_new
  post '/tips' => 'tips#create'
  patch '/tips/:id' => 'tips#update'

  resources :users, only: [:index, :edit, :update, :create, :destroy]
  resources :countries, only: [:index, :edit, :update, :create, :destroy]
  resources :tags, only: [:index, :show, :edit, :update, :create, :destroy]
  resources :destinations, only: [:show, :edit, :update, :create, :destroy]
  resources :tips, only: [:create]
  

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	belongs_to :tag
	has_many :messages
	has_many :tips
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
	before_action :require_user, only: [:show, :index]
	before_action :require_editor, only: [:edit, :update, :new]
	before_action :require_admin, only: [:destroy, :create]
	
	def index
		@destination = Destination.all
	end

	def show
		@destination = Destination.find(params[:id])
		@tips = @destination.tips
	end
	
	def edit
	 @destination = Destination.find(params[:id])
	end

	def update
	 @destination =Destination.find(params[:id])
	  if
	 @destination.update_attributes(destination_params)
		redirect_to @destination, notice: "Destination updated successfully."
	  else
		render 'edit'
	  end
	end

	def new
		@destination = Destination.new
	end

	def create
		t = Time.now.strftime("%Y%m%d%H%M%S")
		uploaded_io = params[:destination][:image]
        File.open(Rails.root.join('public', 'uploads', 'destinations', uploaded_io.original_filename), 'wb') do |file|
     	file.write(uploaded_io.read)
        end

		@destination = Destination.new(destination_params)
		@destination.tag_id = tag_id
		if @destination.save
			redirect_to "/tags", notice: "Destination created successfully!"
		else
			redirect_to edit_destination_path, error: "Destination could not be created."

		end
	end

	def destroy
		@destination = Destination.find(params[:id])
		@destination.destroy
		redirect_to "/tags", alert: "Destination destroyed succesfully."
	end

	def message
		@message = Message.new
	end

	def messages
		@messages = Message.all
	end

	private
	
	def destination_params
	params.require(:destination).permit(:name, :description, :image, :tag_id)
	 end
	end

app/helpers/destination_helper.rb
module DestinationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/edit.html.erb
<div class="destination">
	<div class="container">
		<div class="app-nav">
				<%= link_to destination_path do %>
				<i class="material-icons">chevron_left</i>
				<% end %>
			</div>
		<div class="edit-form">
			<img class="img-responsive" src="<%= @destination.image %>"/>
			<%= form_for(@destination) do |f| %>
				<label for="image"> Image Url </edit>
				<%= f.text_field :image %>
				<label for="destination"> Destination Name </label>
				<%= f.text_field :name %>
				<label for="tag-id"> Tag ID </label>
				<%= f.text_field :tag_id %>
				<label for="destination"> Destination Description</label>
				<%= f.text_area :description %>
				<div class="submit">
				<%= f.submit "Update", :class => "btn-submit", :id => "btn" %>
			<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class="clear-fix">
	</div>

app/views/destinations/index.html.erb
<div class="destinations">
	<div class="page-nav">
		<div class="dropdown">
 			<button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   				<i class="material-icons" id="filter">filter_list</i>
    			<span class="caret"></span>
  			</button>
  			<ul class="dropdown-menu" id="filter-menu" aria-labelledby="dLabel">
    			<li><i class="material-icons">sort_by_alpha</i>Name</li>
				<li><i class="material-icons">favorite</i>Most Visited</li>
				<li><i class="material-icons">whatshot</i>Hottest</li>
				<li><i class="material-icons">trending_up</i>Trending</li>
				<li><i class="material-icons">my_location</i>Near Me</li>
  			</ul>
		</div>
		<h2> Products </h2>
		<ul class="pull-right">
			<li class="square"><i class="material-icons" id="square">reorder</i></li>
			<li class="squares"><i class="material-icons">apps</i></li>
		</ul>
	</div>
	<div class="container">
		<div class="app-nav">
			<% if current_user && current_user.admin? || current_user.editor?() %>
				<%= link_to create_destination_path(@new) do %>
					<i class="material-icons">add_circle</i>
				<% end %>
			<% end %>
		</div>
		<div class="cards row">
			<% @destination.each do |t| %>				
			<div class="card col-md-3 col-xs-11">
				<img class="img-responsive" id="tags" src="<%= t.image %>"/>
				<h2><%= t.name %></h2>
				<p><%= t.description %></p>
				<%= link_to destination_path(t) do %>
				<div class="card-action">
					<i class="material-icons">remove_red_eye</i>
				<% end %>
				<i class="material-icons">favorite_border</i>
				<%= link_to tag_path(t) do %>
					<i class="material-icons">location_on</i>
				<% end %>
				<%= link_to tag_path(t) do %>
					<i class="material-icons">loyalty</i>
				<% end %>
				<% if current_user && current_user.admin?() %>
					<%= link_to destination_path(t), method: "delete", data: {confirm: "Are you sure you want to delete this?"} do %>
					<i class="material-icons">delete_forever</i>
					<% end %>
				<% end %>	
				<% if current_user && current_user.admin? || current_user.editor?() %>
					<%= link_to edit_destination_path(t) do %>
					<i class="material-icons">mode_edit</i>
					<% end %>
				<% end %>
				</div>		
			</div>
			<% end %>
		</div>
	</div>
</div>
<div class="clear-fix">
</div>

app/views/destinations/new.html.erb
<div class="new-destination">
	<div class="container">
		<div class="col-md-4 col-xs-4 col-md-offset-8 col-xs-offset-3">
			<% flash.each do |name, msg| -%>
    		<%= content_tag :div, msg, class: name %>
    		<% end -%>
		</div>

		<div class="app-nav">
			<%= link_to :back do %>
				<i class="material-icons">chevron_left</i>
			<% end %>
		</div>

		<h1> New Product </h1>
		<%= form_for(@destination) do |f|%>
		<div class="form-group">
			<label for="name"> Product Name </label>
			<%= f.text_field :name %>
		</div>
		<div class="form-group">
			<label for="image"> Product Image </label>
			<%= f.file_field :image %>
		</div>
		<div class="form-group">
			<label for="description"> Product Description </label>
			<%= f.text_field :description %>
			<label for="tag-id"> Tag ID </label>
			<%= f.text_field :tag_id %>
			<div class="submit">
			<%= f.submit "Create Destination", class: "btn-submit", method: "create" %>
			</div>
		</div>
		<% end %>
	</div>
</div>
<div class="clear-fix">
</div>

app/views/destinations/show.html.erb
<div class="destinations">
	<div class="page-nav">
		<div class="dropdown">
 			<button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   				<i class="material-icons" id="filter">filter_list</i>
    			<span class="caret"></span>
  			</button>
  			<ul class="dropdown-menu" id="filter-menu" aria-labelledby="dLabel">
    			<li><i class="material-icons">sort_by_alpha</i>Name</li>
				<li><i class="material-icons">favorite</i>Most Visited</li>
				<li><i class="material-icons">whatshot</i>Hottest</li>
				<li><i class="material-icons">trending_up</i>Trending</li>
				<li><i class="material-icons">my_location</i>Near Me</li>
  			</ul>
		</div>
		<h2><%= @destination.name %></h2>
			<ul class="pull-right">
				<li class="square"><i class="material-icons" id="square">reorder</i></li>
				<li class="squares"><i class="material-icons">apps</i></li>
			</ul>
	
	</div>
	<div class= "container">
		<div class="col-md-4 col-xs-4 col-md-offset-8 col-xs-offset-3">
				<% flash.each do |name, msg| -%>
    			<%= content_tag :div, msg, class: name %>
    			<% end %>
			</div>
		<div class="app-nav">
			<%= link_to @destination.tag do %>
			<i class="material-icons">chevron_left</i>
			<% end %>
		</div>
		<div class="destination row">
			<div class="col-md-6 col-xs-11">
				<img class="img-responsive" src="<%= @destination.image %>"/>
				<h2><%= @destination.name %></h2>
				<p><%= @destination.description %></p>
				<div class="action-card">
				<%if current_user && current_user.editor? || current_user.admin? %>
					<%= link_to edit_destination_path(@destination) do %>
					<i class="material-icons">mode_edit</i>
					<% end %>
				<% end %>
				<% if current_user && current_user.admin?() %>
					<%= link_to destination_path(@destination), method: "delete",data: {confirm: "Are you sure you want to delete this?"} do %>
					<i class="material-icons">delete_forever</i>
					<% end %>
				</div>
				<% end %>
			</div>
		</div>
		<div class="col-md-5 pull-right col-xs-12">
				<h3>Tips</h3>
				<% if current_user %>
				<div class="tip-form">
					<%= form_for(message) do |f| %>
						<%= f.text_area :content , :placeholder => "Share a tip about this place in 160 characters or less" %>
						<%= f.submit "Tip", :class => "btn pull-right" %>	
					<% end %>

					
				</div>
				<% end %>
			</div>
	</div>
</div>
<div class="clear-fix">
</div>